/*
Saviynt EIC API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saviynt

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// AnalyticsAPIService AnalyticsAPI service
type AnalyticsAPIService service

type ApiFetchRuntimeControlsDataV2Request struct {
	ctx context.Context
	ApiService *AnalyticsAPIService
	fetchRuntimeControlsDataV2 *FetchRuntimeControlsDataV2
}

// 
func (r ApiFetchRuntimeControlsDataV2Request) FetchRuntimeControlsDataV2(fetchRuntimeControlsDataV2 FetchRuntimeControlsDataV2) ApiFetchRuntimeControlsDataV2Request {
	r.fetchRuntimeControlsDataV2 = &fetchRuntimeControlsDataV2
	return r
}

func (r ApiFetchRuntimeControlsDataV2Request) Execute() (*http.Response, error) {
	return r.ApiService.FetchRuntimeControlsDataV2Execute(r)
}

/*
FetchRuntimeControlsDataV2 Fetch Runtime Controls Data V2

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiFetchRuntimeControlsDataV2Request
*/
func (a *AnalyticsAPIService) FetchRuntimeControlsDataV2(ctx context.Context) ApiFetchRuntimeControlsDataV2Request {
	return ApiFetchRuntimeControlsDataV2Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *AnalyticsAPIService) FetchRuntimeControlsDataV2Execute(r ApiFetchRuntimeControlsDataV2Request) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AnalyticsAPIService.FetchRuntimeControlsDataV2")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/fetchRuntimeControlsDataV2"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.fetchRuntimeControlsDataV2
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
