/*
Saviynt Enterprise Identity Cloud (EIC) API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saviynt

import (
	"encoding/json"
)

// checks if the FetchRuntimeControlsDataRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchRuntimeControlsDataRequest{}

// FetchRuntimeControlsDataRequest struct for FetchRuntimeControlsDataRequest
type FetchRuntimeControlsDataRequest struct {
	Analyticsid *string `json:"analyticsid,omitempty"`
	Analyticsname *string `json:"analyticsname,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Max *string `json:"max,omitempty"`
	Offset *string `json:"offset,omitempty"`
	Loggedinuser *string `json:"loggedinuser,omitempty"`
}

// NewFetchRuntimeControlsDataRequest instantiates a new FetchRuntimeControlsDataRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchRuntimeControlsDataRequest() *FetchRuntimeControlsDataRequest {
	this := FetchRuntimeControlsDataRequest{}
	return &this
}

// NewFetchRuntimeControlsDataRequestWithDefaults instantiates a new FetchRuntimeControlsDataRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchRuntimeControlsDataRequestWithDefaults() *FetchRuntimeControlsDataRequest {
	this := FetchRuntimeControlsDataRequest{}
	return &this
}

// GetAnalyticsid returns the Analyticsid field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetAnalyticsid() string {
	if o == nil || IsNil(o.Analyticsid) {
		var ret string
		return ret
	}
	return *o.Analyticsid
}

// GetAnalyticsidOk returns a tuple with the Analyticsid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetAnalyticsidOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsid) {
		return nil, false
	}
	return o.Analyticsid, true
}

// HasAnalyticsid returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasAnalyticsid() bool {
	if o != nil && !IsNil(o.Analyticsid) {
		return true
	}

	return false
}

// SetAnalyticsid gets a reference to the given string and assigns it to the Analyticsid field.
func (o *FetchRuntimeControlsDataRequest) SetAnalyticsid(v string) {
	o.Analyticsid = &v
}

// GetAnalyticsname returns the Analyticsname field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetAnalyticsname() string {
	if o == nil || IsNil(o.Analyticsname) {
		var ret string
		return ret
	}
	return *o.Analyticsname
}

// GetAnalyticsnameOk returns a tuple with the Analyticsname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetAnalyticsnameOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsname) {
		return nil, false
	}
	return o.Analyticsname, true
}

// HasAnalyticsname returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasAnalyticsname() bool {
	if o != nil && !IsNil(o.Analyticsname) {
		return true
	}

	return false
}

// SetAnalyticsname gets a reference to the given string and assigns it to the Analyticsname field.
func (o *FetchRuntimeControlsDataRequest) SetAnalyticsname(v string) {
	o.Analyticsname = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *FetchRuntimeControlsDataRequest) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *FetchRuntimeControlsDataRequest) SetMax(v string) {
	o.Max = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetOffset() string {
	if o == nil || IsNil(o.Offset) {
		var ret string
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetOffsetOk() (*string, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given string and assigns it to the Offset field.
func (o *FetchRuntimeControlsDataRequest) SetOffset(v string) {
	o.Offset = &v
}

// GetLoggedinuser returns the Loggedinuser field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataRequest) GetLoggedinuser() string {
	if o == nil || IsNil(o.Loggedinuser) {
		var ret string
		return ret
	}
	return *o.Loggedinuser
}

// GetLoggedinuserOk returns a tuple with the Loggedinuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataRequest) GetLoggedinuserOk() (*string, bool) {
	if o == nil || IsNil(o.Loggedinuser) {
		return nil, false
	}
	return o.Loggedinuser, true
}

// HasLoggedinuser returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataRequest) HasLoggedinuser() bool {
	if o != nil && !IsNil(o.Loggedinuser) {
		return true
	}

	return false
}

// SetLoggedinuser gets a reference to the given string and assigns it to the Loggedinuser field.
func (o *FetchRuntimeControlsDataRequest) SetLoggedinuser(v string) {
	o.Loggedinuser = &v
}

func (o FetchRuntimeControlsDataRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchRuntimeControlsDataRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Analyticsid) {
		toSerialize["analyticsid"] = o.Analyticsid
	}
	if !IsNil(o.Analyticsname) {
		toSerialize["analyticsname"] = o.Analyticsname
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Loggedinuser) {
		toSerialize["loggedinuser"] = o.Loggedinuser
	}
	return toSerialize, nil
}

type NullableFetchRuntimeControlsDataRequest struct {
	value *FetchRuntimeControlsDataRequest
	isSet bool
}

func (v NullableFetchRuntimeControlsDataRequest) Get() *FetchRuntimeControlsDataRequest {
	return v.value
}

func (v *NullableFetchRuntimeControlsDataRequest) Set(val *FetchRuntimeControlsDataRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchRuntimeControlsDataRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchRuntimeControlsDataRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchRuntimeControlsDataRequest(val *FetchRuntimeControlsDataRequest) *NullableFetchRuntimeControlsDataRequest {
	return &NullableFetchRuntimeControlsDataRequest{value: val, isSet: true}
}

func (v NullableFetchRuntimeControlsDataRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchRuntimeControlsDataRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


