/*
Saviynt Enterprise Identity Cloud (EIC) API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saviynt

import (
	"encoding/json"
)

// checks if the FetchControlDetailsESRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchControlDetailsESRequest{}

// FetchControlDetailsESRequest struct for FetchControlDetailsESRequest
type FetchControlDetailsESRequest struct {
	Analyticsid *string `json:"analyticsid,omitempty"`
	Analyticsname *string `json:"analyticsname,omitempty"`
	Loggedinuser *string `json:"loggedinuser,omitempty"`
	Max *string `json:"max,omitempty"`
	Offset *string `json:"offset,omitempty"`
	Filtercriteria map[string]interface{} `json:"filtercriteria,omitempty"`
}

// NewFetchControlDetailsESRequest instantiates a new FetchControlDetailsESRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchControlDetailsESRequest() *FetchControlDetailsESRequest {
	this := FetchControlDetailsESRequest{}
	return &this
}

// NewFetchControlDetailsESRequestWithDefaults instantiates a new FetchControlDetailsESRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchControlDetailsESRequestWithDefaults() *FetchControlDetailsESRequest {
	this := FetchControlDetailsESRequest{}
	return &this
}

// GetAnalyticsid returns the Analyticsid field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetAnalyticsid() string {
	if o == nil || IsNil(o.Analyticsid) {
		var ret string
		return ret
	}
	return *o.Analyticsid
}

// GetAnalyticsidOk returns a tuple with the Analyticsid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetAnalyticsidOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsid) {
		return nil, false
	}
	return o.Analyticsid, true
}

// HasAnalyticsid returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasAnalyticsid() bool {
	if o != nil && !IsNil(o.Analyticsid) {
		return true
	}

	return false
}

// SetAnalyticsid gets a reference to the given string and assigns it to the Analyticsid field.
func (o *FetchControlDetailsESRequest) SetAnalyticsid(v string) {
	o.Analyticsid = &v
}

// GetAnalyticsname returns the Analyticsname field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetAnalyticsname() string {
	if o == nil || IsNil(o.Analyticsname) {
		var ret string
		return ret
	}
	return *o.Analyticsname
}

// GetAnalyticsnameOk returns a tuple with the Analyticsname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetAnalyticsnameOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsname) {
		return nil, false
	}
	return o.Analyticsname, true
}

// HasAnalyticsname returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasAnalyticsname() bool {
	if o != nil && !IsNil(o.Analyticsname) {
		return true
	}

	return false
}

// SetAnalyticsname gets a reference to the given string and assigns it to the Analyticsname field.
func (o *FetchControlDetailsESRequest) SetAnalyticsname(v string) {
	o.Analyticsname = &v
}

// GetLoggedinuser returns the Loggedinuser field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetLoggedinuser() string {
	if o == nil || IsNil(o.Loggedinuser) {
		var ret string
		return ret
	}
	return *o.Loggedinuser
}

// GetLoggedinuserOk returns a tuple with the Loggedinuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetLoggedinuserOk() (*string, bool) {
	if o == nil || IsNil(o.Loggedinuser) {
		return nil, false
	}
	return o.Loggedinuser, true
}

// HasLoggedinuser returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasLoggedinuser() bool {
	if o != nil && !IsNil(o.Loggedinuser) {
		return true
	}

	return false
}

// SetLoggedinuser gets a reference to the given string and assigns it to the Loggedinuser field.
func (o *FetchControlDetailsESRequest) SetLoggedinuser(v string) {
	o.Loggedinuser = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *FetchControlDetailsESRequest) SetMax(v string) {
	o.Max = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetOffset() string {
	if o == nil || IsNil(o.Offset) {
		var ret string
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetOffsetOk() (*string, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given string and assigns it to the Offset field.
func (o *FetchControlDetailsESRequest) SetOffset(v string) {
	o.Offset = &v
}

// GetFiltercriteria returns the Filtercriteria field value if set, zero value otherwise.
func (o *FetchControlDetailsESRequest) GetFiltercriteria() map[string]interface{} {
	if o == nil || IsNil(o.Filtercriteria) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filtercriteria
}

// GetFiltercriteriaOk returns a tuple with the Filtercriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchControlDetailsESRequest) GetFiltercriteriaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filtercriteria) {
		return map[string]interface{}{}, false
	}
	return o.Filtercriteria, true
}

// HasFiltercriteria returns a boolean if a field has been set.
func (o *FetchControlDetailsESRequest) HasFiltercriteria() bool {
	if o != nil && !IsNil(o.Filtercriteria) {
		return true
	}

	return false
}

// SetFiltercriteria gets a reference to the given map[string]interface{} and assigns it to the Filtercriteria field.
func (o *FetchControlDetailsESRequest) SetFiltercriteria(v map[string]interface{}) {
	o.Filtercriteria = v
}

func (o FetchControlDetailsESRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchControlDetailsESRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Analyticsid) {
		toSerialize["analyticsid"] = o.Analyticsid
	}
	if !IsNil(o.Analyticsname) {
		toSerialize["analyticsname"] = o.Analyticsname
	}
	if !IsNil(o.Loggedinuser) {
		toSerialize["loggedinuser"] = o.Loggedinuser
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Filtercriteria) {
		toSerialize["filtercriteria"] = o.Filtercriteria
	}
	return toSerialize, nil
}

type NullableFetchControlDetailsESRequest struct {
	value *FetchControlDetailsESRequest
	isSet bool
}

func (v NullableFetchControlDetailsESRequest) Get() *FetchControlDetailsESRequest {
	return v.value
}

func (v *NullableFetchControlDetailsESRequest) Set(val *FetchControlDetailsESRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchControlDetailsESRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchControlDetailsESRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchControlDetailsESRequest(val *FetchControlDetailsESRequest) *NullableFetchControlDetailsESRequest {
	return &NullableFetchControlDetailsESRequest{value: val, isSet: true}
}

func (v NullableFetchControlDetailsESRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchControlDetailsESRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


