/*
Saviynt EIC API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package saviynt

import (
	"encoding/json"
)

// checks if the FetchRuntimeControlsDataV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchRuntimeControlsDataV2{}

// FetchRuntimeControlsDataV2 struct for FetchRuntimeControlsDataV2
type FetchRuntimeControlsDataV2 struct {
	Requestor *string `json:"requestor,omitempty"`
	Analyticsname *string `json:"analyticsname,omitempty"`
	Analyticsid *string `json:"analyticsid,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Max *string `json:"max,omitempty"`
	Offset *string `json:"offset,omitempty"`
}

// NewFetchRuntimeControlsDataV2 instantiates a new FetchRuntimeControlsDataV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFetchRuntimeControlsDataV2() *FetchRuntimeControlsDataV2 {
	this := FetchRuntimeControlsDataV2{}
	return &this
}

// NewFetchRuntimeControlsDataV2WithDefaults instantiates a new FetchRuntimeControlsDataV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFetchRuntimeControlsDataV2WithDefaults() *FetchRuntimeControlsDataV2 {
	this := FetchRuntimeControlsDataV2{}
	return &this
}

// GetRequestor returns the Requestor field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetRequestor() string {
	if o == nil || IsNil(o.Requestor) {
		var ret string
		return ret
	}
	return *o.Requestor
}

// GetRequestorOk returns a tuple with the Requestor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetRequestorOk() (*string, bool) {
	if o == nil || IsNil(o.Requestor) {
		return nil, false
	}
	return o.Requestor, true
}

// HasRequestor returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasRequestor() bool {
	if o != nil && !IsNil(o.Requestor) {
		return true
	}

	return false
}

// SetRequestor gets a reference to the given string and assigns it to the Requestor field.
func (o *FetchRuntimeControlsDataV2) SetRequestor(v string) {
	o.Requestor = &v
}

// GetAnalyticsname returns the Analyticsname field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetAnalyticsname() string {
	if o == nil || IsNil(o.Analyticsname) {
		var ret string
		return ret
	}
	return *o.Analyticsname
}

// GetAnalyticsnameOk returns a tuple with the Analyticsname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetAnalyticsnameOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsname) {
		return nil, false
	}
	return o.Analyticsname, true
}

// HasAnalyticsname returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasAnalyticsname() bool {
	if o != nil && !IsNil(o.Analyticsname) {
		return true
	}

	return false
}

// SetAnalyticsname gets a reference to the given string and assigns it to the Analyticsname field.
func (o *FetchRuntimeControlsDataV2) SetAnalyticsname(v string) {
	o.Analyticsname = &v
}

// GetAnalyticsid returns the Analyticsid field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetAnalyticsid() string {
	if o == nil || IsNil(o.Analyticsid) {
		var ret string
		return ret
	}
	return *o.Analyticsid
}

// GetAnalyticsidOk returns a tuple with the Analyticsid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetAnalyticsidOk() (*string, bool) {
	if o == nil || IsNil(o.Analyticsid) {
		return nil, false
	}
	return o.Analyticsid, true
}

// HasAnalyticsid returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasAnalyticsid() bool {
	if o != nil && !IsNil(o.Analyticsid) {
		return true
	}

	return false
}

// SetAnalyticsid gets a reference to the given string and assigns it to the Analyticsid field.
func (o *FetchRuntimeControlsDataV2) SetAnalyticsid(v string) {
	o.Analyticsid = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *FetchRuntimeControlsDataV2) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *FetchRuntimeControlsDataV2) SetMax(v string) {
	o.Max = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *FetchRuntimeControlsDataV2) GetOffset() string {
	if o == nil || IsNil(o.Offset) {
		var ret string
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FetchRuntimeControlsDataV2) GetOffsetOk() (*string, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *FetchRuntimeControlsDataV2) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given string and assigns it to the Offset field.
func (o *FetchRuntimeControlsDataV2) SetOffset(v string) {
	o.Offset = &v
}

func (o FetchRuntimeControlsDataV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchRuntimeControlsDataV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requestor) {
		toSerialize["requestor"] = o.Requestor
	}
	if !IsNil(o.Analyticsname) {
		toSerialize["analyticsname"] = o.Analyticsname
	}
	if !IsNil(o.Analyticsid) {
		toSerialize["analyticsid"] = o.Analyticsid
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableFetchRuntimeControlsDataV2 struct {
	value *FetchRuntimeControlsDataV2
	isSet bool
}

func (v NullableFetchRuntimeControlsDataV2) Get() *FetchRuntimeControlsDataV2 {
	return v.value
}

func (v *NullableFetchRuntimeControlsDataV2) Set(val *FetchRuntimeControlsDataV2) {
	v.value = val
	v.isSet = true
}

func (v NullableFetchRuntimeControlsDataV2) IsSet() bool {
	return v.isSet
}

func (v *NullableFetchRuntimeControlsDataV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFetchRuntimeControlsDataV2(val *FetchRuntimeControlsDataV2) *NullableFetchRuntimeControlsDataV2 {
	return &NullableFetchRuntimeControlsDataV2{value: val, isSet: true}
}

func (v NullableFetchRuntimeControlsDataV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFetchRuntimeControlsDataV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


