/*
Saviynt EIC API

Testing AnalyticsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package saviynt

import (
	"context"
	"testing"

	"github.com/saviynt/gosaviynt/saviynt"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_saviynt_AnalyticsAPIService(t *testing.T) {
	configuration := saviynt.NewConfiguration()
	apiClient := saviynt.NewAPIClient(configuration)

	t.Run("Test AnalyticsAPIService FetchRuntimeControlsDataV2", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.AnalyticsAPI.FetchRuntimeControlsDataV2(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
